server:
  port: 8081
  servlet:
    context-path: /api
  spring:
    datasource:
#      url: "jdbc:mariadb://localhost:3306/doctor-appointment"
      url: "jdbc:mysql://localhost:3306/doctor-appointment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh"
      driverClassName: "org.mariadb.jdbc.Driver"
      username: root
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
